name: linters-and-tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  linters_and_tests:
    name: Run linters and tests
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: "3.7"
          - python_version: "3.8"
          - python_version: "3.9"
          - python_version: "3.10"
          - python_version: "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Create virtual env
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements-dev.txt
          pip install .

      - name: Run lint
        run: |
          source venv/bin/activate
          ruff check redfish_client tests

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests
